version: "3.8"

services:
  streamlit:
    build:
      context: ../streamlit
      dockerfile: Dockerfile
    container_name: streamlit_app
    ports:
      - "8502:8502"
    volumes:
      - ../data:/app/data
    networks:
      - mlops-network
    depends_on:
      - mlflow

  mlflow:
    image: ghcr.io/mlflow/mlflow:v2.21.0
    container_name: mlflow
    command: mlflow server --host 0.0.0.0 --port 8080
    ports:
      - "8080:8080"
    networks:
      - mlops-network

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - mlops-network

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    networks:
      - mlops-network

networks:
  mlops-network:
    driver: bridge
