global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'streamlit_app'
    static_configs:
      - targets: ['streamlit_app:8001']
